- App.js
- components/FormInput.js
- navigation/BottomTabNavigator.js
- package-lock.json
- package.json
- screens/HomeScreen.js
- screens/SignIn.js
- screens/SignUp.js
- services/aws/index.js
- services/parse/auth/index.js
Updated the sign up and sign in pages to use a formik component. Added sign up and sign in pages to initial application load. Added validation to the form inputs using Yup.
- [x ] My lint and unit tests pass locally with my changes
The validation schema will need to be refined and updated in the future.
> Platform 127

- components/PaperInput/index.js
- domains/DataCollection/Forms/PatientID/config.js
- domains/DataCollection/Forms/PatientID/index.js
- domains/DataCollection/index.js
- domains/HomeScreen/index.js
> PLATFORM-92 - WIP- Patient ID form

- domains/DataCollection/Forms/PatientID/config.js
> chore: add options for education

- components/FormikFields/PaperInputPicker/index.js
- domains/DataCollection/Forms/IdentificationForm/index.js
> PLATFORM-52 - Adding Altitude

- components/FormikFields/PaperInputPicker/HouseholdManager/index.js
- components/ResidentIdSearchbar/index.js
- services/parse/crud/index.js
> fix: switch querying function

- README.md
- components/FindResidents/index.js
- components/FormikFields/PaperInputPicker/index.js
- components/Header/index.styles.js
- components/MainNavigation/index.js
- domains/DataCollection/FormGallery/index.js
- domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
- domains/DataCollection/Forms/SupplementaryForm/configs/medical-evaluation.config.js
- domains/DataCollection/Forms/SupplementaryForm/index.js
- domains/DataCollection/Forms/index.js
- domains/DataCollection/index.js
- modules/theme/index.js
- modules/theme/layout/index.js
- package.json
> PLATFORM-159 - WIP - Create UI for "View All Forms" screen

- domains/DataCollection/FormGallery/index.js
- domains/DataCollection/Forms/index.js
- domains/DataCollection/index.js
- modules/theme/layout/index.js
These provide functions to bring navigation to the highest level of the data collection domain @jamccomb92 . You should be able to use `navigateToNewRecord` to navigate to the appropriate forms in your `Find Records` work
> feat: refactor navigation 

- domains/DataCollection/Forms/IdentificationForm/index.js
- domains/DataCollection/Forms/SupplementaryForm/index.js
- domains/DataCollection/Forms/index.js
- domains/DataCollection/index.js
- modules/theme/layout/index.js
and add `surveyingOrganization` to the identification form
> PLATFORM-158 - Create ability to add resident to supplementary forms

- domains/HomeScreen/index.js
Adds titles form home screen, not much else tbh.....
> Platform 143

- CHANGELOG.md
- app.json
- components/FindResidents/Resident/ResidentCard/index.js
- components/FindResidents/index.js
- components/FormikFields/PaperInputPicker/HouseholdManager/index.js
- components/FormikFields/PaperInputPicker/index.js
- components/ResidentIdSearchbar/index.js
- domains/DataCollection/Forms/IdentificationForm/config/config.js
- domains/DataCollection/Forms/IdentificationForm/index.js
- domains/DataCollection/Forms/SupplementaryForm/index.js
- domains/DataCollection/Forms/index.js
- domains/DataCollection/index.js
- domains/HomeScreen/index.js
- package.json
Made fixes to the objectId that was being carried from the identification form to subsequent forms
> fix: objectId wasn't being carried to new forms being created

- components/Cards/SmallCardsCarousel/index.js
- components/FindResidents/Resident/ResidentPage/Forms/index.js
- domains/DataCollection/FormGallery/index.js
- domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
- domains/DataCollection/Forms/SupplementaryForm/index.js
- domains/DataCollection/Forms/index.js
- domains/DataCollection/index.js
- modules/theme/layout/index.js
- services/parse/crud/custom-queries/index.js
- services/parse/crud/index.js
Pulls in the user's organization custom forms
> PLATFORM-166 - Fix Custom Forms Work

- CHANGELOG.md
- app.json
- components/FindResidents/index.js
- components/MainNavigation/BottomTabNavigator./index.js
- components/MapView/index.js
- domains/DataCollection/index.js
- domains/DataCollection/index.styles.js
- package-lock.json
- package.json
- services/parse/crud/index.js
> chore: add map view

- components/Header/index.js
- components/Header/index.styles.js
- domains/Auth/SignIn/index.js
- domains/DataCollection/index.js
- package-lock.json
- package.json
- services/parse/calculate/index.js
> chore: add abilities to header

- domains/DataCollection/FormGallery/index.js
- domains/DataCollection/index.js
> Platform 165

- components/Cards/SmallCardsCarousel/index.js
- components/FindResidents/Resident/ResidentCard/index.js
- components/FindResidents/Resident/ResidentPage/Demographics/index.js
- components/FindResidents/Resident/ResidentPage/Forms/index.js
- components/FindResidents/Resident/ResidentPage/index.js
- components/FindResidents/index.js
- components/FormikFields/PaperInputPicker/HouseholdManager/index.js
- components/Header/index.js
- components/LanguagePicker/index.js
- components/ResidentIdSearchbar/index.js
- components/TermsModal/index.js
- domains/Auth/PinCode/GetPinCode/index.js
- domains/Auth/PinCode/StorePinCode/index.js
- domains/Auth/SignIn/CredentialsModal/index.js
- domains/Auth/SignIn/ForgotPassword/index.js
- domains/Auth/SignIn/index.js
- domains/Auth/SignUp/index.js
- domains/DataCollection/FormGallery/index.js
- domains/DataCollection/Forms/IdentificationForm/config/config.js
- domains/DataCollection/Forms/IdentificationForm/index.js
- domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
- domains/DataCollection/Forms/SupplementaryForm/configs/medical-evaluation.config.js
- domains/DataCollection/Forms/SupplementaryForm/index.js
- domains/DataCollection/Forms/index.js
- domains/DataCollection/GdprCompliance/index.js
- domains/DataCollection/index.js
- domains/HomeScreen/index.js
- modules/i18n/english/en.json
- modules/i18n/spanish/es.json
Adds I18n localization for english and spanish. Spanish translations needed.
> Platform 65

- components/FormikFields/PaperInputPicker/HouseholdManager/index.js
- components/FormikFields/PaperInputPicker/HouseholdManager/index.style.js
- components/FormikFields/PaperInputPicker/index.js
- components/ResidentIdSearchbar/index.js
- components/ResidentIdSearchbar/index.styles.js
- domains/DataCollection/FormGallery/index.js
- domains/DataCollection/Forms/IdentificationForm/index.js
fixes issues with the household view
> Fix household view

- components/FormikFields/PaperInputPicker/HouseholdManager/index.js
Adds numinputs to Environmental health
adds new questions to env health
adds community to the resident card
> Env health fixes

- CHANGELOG.md
- app.json
- modules/i18n/spanish/es.json
- package-lock.json
- package.json
- services/aws/index.js
- services/parse/auth/index.js
- services/tasky/tasks/index.js
Fixes a problem where a deprecated library was blocking Android (and eventually iOS) from connecting with the Parse API
> Deployment fixes 10 26

- CHANGELOG.md
- app.json
- domains/Auth/SignIn/index.js
- modules/async-storage/index.js
- package-lock.json
- package.json
- services/parse/auth/index.js
> PLATFORM-176 - Android problems

- App.js
- CHANGELOG.md
- README.md
- app.json
- domains/Auth/SignIn/index.js
- domains/DataCollection/index.js
- package-lock.json
- package.json
MapView making android crash
I hate that this took that long to figure out
> Remove MapView from Android

- components/FormikFields/PaperInputPicker/AutoFill/index.js
- components/FormikFields/YupValidation/index.js
- domains/DataCollection/Forms/IdentificationForm/config/config.js
- modules/i18n/english/en.json
- modules/i18n/spanish/es.json
> PLATFORM-90

- domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
- domains/DataCollection/Forms/SupplementaryForm/configs/medical-evaluation.config.js
> fix: remove validation on environmental health config

- components/Cards/SmallCardsCarousel/index.js
- components/FormikFields/PaperInputPicker/index.js
- components/FormikFields/PaperInputPicker/index.style.js
- domains/Auth/SignUp/index.js
- domains/DataCollection/Forms/SupplementaryForm/configs/vitals.config.js
- domains/DataCollection/Forms/SupplementaryForm/index.js
- domains/DataCollection/Forms/SupplementaryForm/utils/index.js
- domains/DataCollection/index.js
- modules/i18n/english/en.json
- modules/i18n/spanish/es.json
Adds the vitals form to supplementary forms with translations.
Need an image for the small card carousel
translations for diastolic/systolic -- blood pressure keys i added -- either need translations or need a different label.
> Platfrom 187

- components/FormikFields/PaperInputPicker/index.js
Adds new paper input picker where question appears above the text input. Possible needs a new name.
inputSideLabelTextQuestNumber
> Platform 189

- components/FormikFields/PaperInputPicker/HouseholdManager/index.js
- components/FormikFields/PaperInputPicker/index.js
- modules/i18n/english/en.json
- modules/i18n/spanish/es.json
Adds household relationships for the household class - sibling, parent etc...
Adds additional UI for cleaner experience
> Platform 161

- domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
- modules/i18n/english/en.json
- modules/i18n/spanish/es.json
translation on environmental health form for roof condition
> fix: translation on environmental health form for roof condition

- domains/DataCollection/Forms/index.js
- domains/DataCollection/index.js
- modules/i18n/english/en.json
- modules/i18n/spanish/es.json
> Platform 197

- domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
- modules/i18n/english/en.json
- modules/i18n/spanish/es.json
> Platform 202

- components/FormikFields/PaperInputPicker/index.js
- domains/DataCollection/Forms/IdentificationForm/config/config.js
- domains/DataCollection/Forms/IdentificationForm/index.js
- domains/DataCollection/Forms/index.js
- domains/DataCollection/index.js
Adds keybaord dismiss on touch outside of input. 
max values for text input - only added to multiInputRowNum for now but logic can be applied to all inputs easily
Did not figure out a way to handle moving to next input for dob on maxlength with our architecture. I believe it would require refs to the inputs but PIP will not allow this
> Platform 195

- domains/DataCollection/Forms/IdentificationForm/config/config.js
- modules/i18n/english/en.json
- modules/i18n/spanish/es.json
> fix: add age as option on id form

- components/FormikFields/PaperInputPicker/index.js
- components/FormikFields/PaperInputPicker/index.style.js
> fix: text wrapping with inputs

- components/FormikFields/PaperInputPicker/index.style.js
- domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
- modules/i18n/english/en.json
- modules/i18n/spanish/es.json
> Platform 220

- components/Cards/SmallCardsCarousel/index.js
- components/FormikFields/PaperInputPicker/AutoFill/index.js
- components/FormikFields/PaperInputPicker/index.js
- components/FormikFields/PaperInputPicker/index.style.js
- domains/DataCollection/FormGallery/index.js
- domains/DataCollection/index.js
- domains/DataCollection/index.styles.js
> Platform 223

- components/MapView/index.js
- domains/Auth/SignIn/index.js
> PLATFORM-203: keyboard not hiding when signing in

- components/FormikFields/PaperInputPicker/index.js
> PLATFORM-207: Grabbing GPS location needs to be more clear while loading

- components/FindResidents/Resident/ResidentPage/index.js
- components/MapView/index.js
> chore: reformat findResident page

- domains/DataCollection/index.js
- domains/HomeScreen/index.js
- modules/cached-resources/index.js
- modules/cached-resources/read.js
- package-lock.json
caches any api driven requests
> Platform 229

- domains/DataCollection/Forms/SupplementaryForm/index.js
Fixes supplementary forms validation logic. only validate on submit now.
> Platform 194

- domains/Auth/SignIn/index.js
- domains/DataCollection/Forms/IdentificationForm/index.js
- domains/DataCollection/Forms/IdentificationForm/utils/index.js
- domains/DataCollection/Forms/SupplementaryForm/index.js
- domains/DataCollection/index.js
- modules/utils/index.js
> feat: hotfix for not populating surveyor names

- components/FormikFields/ErrorPicker/index.js
- domains/DataCollection/Forms/index.js
- domains/DataCollection/index.js
Fixes return home after successful form submission
> Platform 253

- domains/DataCollection/Forms/SupplementaryForm/configs/envhealth.config.js
fix environmental health option
> PLATFORM-268:  Fix add other as option to env health

- domains/DataCollection/Forms/SupplementaryForm/configs/vitals.config.js
- modules/i18n/english/en.json
- modules/i18n/spanish/es.json
> PLATFORM 270: Vital Form Fixes

- domains/DataCollection/Forms/SupplementaryForm/index.js
Add surveyingUser and surveyingOrganization to each custom form
> fix: add surveyingUser and surveyingOrganization to custom forms

- domains/Auth/PinCode/GetPinCode/index.js
- modules/cached-resources/populate-cache.js
This reverts commit 5c999bdee8cad49056060f4aa02bead7479b084b.
> Revert "chore: rollback PLATFORM-261"

- domains/DataCollection/Forms/IdentificationForm/index.js
- domains/DataCollection/Forms/SupplementaryForm/index.js
Fixes activity indicator when user submits a form. (waits 10 seconds at the max if no response)
> Platform 281

- domains/Auth/SignIn/index.js
- modules/cached-resources/index.js
- modules/cached-resources/populate-cache.js
- modules/cached-resources/read.js
Pulls custom forms and ID forms on sign in
> Platform 282

- domains/DataCollection/index.js
> fix: remove deletes

- components/ResidentIdSearchbar/index.js
Stops continuous loading when offline for resident Searchbar on refresh
> Refresh fix

- App.js
- domains/Auth/SignIn/index.js
- domains/DataCollection/Forms/IdentificationForm/index.js
- domains/DataCollection/Forms/SupplementaryForm/index.js
- modules/cached-resources/populate-cache.js
- package-lock.json
Add appVersion to async and all form submissions
> Platform 108

- CHANGELOG.md
- app.json
- modules/cached-resources/Post/Offline/forms.js
- modules/cached-resources/Post/post.js
- package.json
Resolves double submission of forms offline and moves the check for finishing postSuppOffline and postIDFormsOffline
> Platform 279

- components/FormikFields/PaperInputPicker/AutoFill/index.js
Fix for text input not responding to users fr android
> Platform 309

- components/ResidentIdSearchbar/index.js
As a data collector, they're able to access every record in the database (when online) so that they can fill out a supplementary form for anyone they've created an identification form for.
[Link to JIRA Ticket](https://puente.atlassian.net/browse/PLATFORM-320)
> Platform 302

- domains/DataCollection/Assets/NewAssets/AssetCore/PeopleModal/index.js
- domains/DataCollection/Assets/NewAssets/AssetCore/index.js
- domains/DataCollection/Assets/NewAssets/AssetSupplementary/index.js
- domains/DataCollection/Assets/NewAssets/index.js
- domains/DataCollection/Assets/ViewAssets/index.js
> chore: cleanup memory leaks and linting before release

- components/ResidentIdSearchbar/index.js
> fix: ability to search first and last name

- README.md
- components/Cards/SmallCardsCarousel/index.js
- components/MainNavigation/BottomTabNavigator./index.js
- domains/DataCollection/FormGallery/index.js
- domains/DataCollection/index.js
- modules/i18n/english/en.json
- modules/i18n/kreyol/hk.json
- modules/i18n/spanish/es.json
> PLATFORM-347: Pinned Forms

- components/ResidentIdSearchbar/index.js
We're still hitting too many requests/second, I'm going to test making the timeout a little longer for searching
> PLATFORM-XXX: Fix for too many requests/s

- domains/DataCollection/FormGallery/index.js
- domains/DataCollection/FormGallery/index.styles.js
- domains/DataCollection/Forms/index.js
- domains/DataCollection/Forms/index.styles.js
- domains/DataCollection/index.js
Put "Pinned forms" on suggested forms page post form submission
> PLATFORM-363: add pinned forms to suggested forms spot

- components/ResidentIdSearchbar/index.js
- components/ResidentIdSearchbar/utils/index.js
Online search was only pulling in the most recent 2000 for some reason still, or defaulted to offline always
> PLATFORM-364

- modules/cached-resources/populate-cache.js
Adds asset forms/query to populate cache on inital sign up. All other leg work for offline work had already been taken care of.
> Platform 370

- components/Header/index.js
- modules/cached-resources/Post/post.js
The submit offline button was triggered by the count of offline forms stored. I simplified the promise structure and logic that sets offline count
> PLATFORM-389: Asset forms offline can't be uploaded by themselves

- domains/Auth/PinCode/GetPinCode/index.js
- domains/Auth/SignIn/index.js
- domains/HomeScreen/index.js
- domains/Settings/SettingsHome/AccountSettings/NamePhoneEmail/index.js
- domains/Settings/SettingsHome/AccountSettings/Password/index.js
- modules/async-storage/index.js
- modules/cached-resources/error-handling.js
We were using two different objects to manage the user and their information, when we only needed one.
I changed all references to `credentials` to `currentUser`. Please let me know if any of the use-cases I changed for credentials will break something
> PLATFORM-418: User object was being mismanaged

- components/PushNotification/index.js
- domains/Auth/SignIn/index.js
- modules/cached-resources/populate-cache.js
- services/parse/auth/index.js
Add expo push token to user object. node cloud PLATFORM-410 required
> Platform 410

- domains/DataCollection/FormGallery/index.js
- domains/DataCollection/index.js
Fixes keyboard dismissing view and uses the hook `useFocusEffect` to get the user to switch
> fix: user not switching when entering data collection epic

- domains/DataCollection/Forms/IdentificationForm/index.js
Fix search index (bug Joey found). 
- I need this to be an array for the search performance I'm working on. 
- I fixed the nickname
- I added another field called `fullTextSearch`. I need to test the performance between searching with an array or with the string, so it probably makes the most sense to just add this field upfront
- I fixed linting errors
I should not code in an airport haha
> PLATFORM-463: Fix Search Index Take 2

- components/Header/FormCounts/index.js
> Platform 473

- domains/DataCollection/Assets/NewAssets/AssetCore/index.js
- domains/DataCollection/Assets/NewAssets/AssetSupplementary/index.js
- domains/DataCollection/Forms/IdentificationForm/index.js
- domains/DataCollection/Forms/SupplementaryForm/index.js
- modules/cached-resources/populate-cache.js
- Added an app version failsafe
- Add phoneOS as a value
> PLATFORM-496: Adding app version failsafe to the submissions

- components/Header/FormCounts/index.js
> chore: add promise.all and update useEffect

- components/FormikFields/PaperInputPicker/Geolocation/index.js
- components/FormikFields/PaperInputPicker/Looper/index.js
- components/FormikFields/PaperInputPicker/index.js
- domains/DataCollection/Assets/NewAssets/AssetCore/index.js
- domains/DataCollection/Assets/NewAssets/AssetSupplementary/index.js
- domains/DataCollection/Forms/IdentificationForm/index.js
- domains/DataCollection/Forms/SupplementaryForm/index.js
- modules/geolocation/index.js
- modules/i18n/english/en.json
- modules/i18n/kreyol/hk.json
- modules/i18n/spanish/es.json
- modules/utils/index.js
> Platform 499

- domains/DataCollection/FormGallery/index.js
- modules/cached-resources/read.js
Only show active custom forms in application
- custom
- asset sup
> Platform 464

- domains/DataCollection/FormGallery/FormsHorizontalView/index.js
- domains/DataCollection/FormGallery/index.js
- domains/DataCollection/FormGallery/index.styles.js
- modules/i18n/english/en.json
- modules/i18n/kreyol/hk.json
- modules/i18n/spanish/es.json
Adds workflows to formGallery and refactors horizontal scroll card view to separate component
> Platform 479

- components/FormikFields/PaperInputPicker/Looper/index.js
- components/FormikFields/PaperInputPicker/index.js
- domains/DataCollection/Assets/NewAssets/AssetCore/index.js
- domains/DataCollection/Assets/NewAssets/AssetSupplementary/index.js
- domains/DataCollection/Forms/SupplementaryForm/index.js
- domains/DataCollection/Forms/SupplementaryForm/utils/index.js
Adds loop for same form submission
ie. concatenates all repeated questions to ooriginal formikKey
> Platform 491

- services/parse/auth/index.js
> fix: firstname and user properties being stored

- services/parse/auth/index.js
> chore: linting

- domains/DataCollection/Forms/IdentificationForm/index.js
- domains/DataCollection/Forms/SupplementaryForm/index.js
- modules/cached-resources/index.js
- modules/cached-resources/populate-cache.js
- modules/cached-resources/read.js
- package-lock.json
Reverts hopetambala/puente-reactnative-collect#468
> Revert "Platform 263: Disabled Puente Forms"

- domains/DataCollection/FormGallery/index.js
Add better logic for custom forms handling in forms gallery
> PLATFORM-559: Add custom forms logic

- modules/offline/index.js
- package-lock.json
- package.json
ADHOC: Use built-in Date() library to track response times and remove easytimer
> ADHOC: Use built-in Date() library to track response times and remove easytimer

- .github/workflows/preview.yaml
This reverts commit e6f1998ce01a540b9ca1c3aaeb4a242107449479.
>  "Adds Expo preview CI job""
